version: '3'
services:
    web:
        build: .
        env_file: .env
        ports:
            - "${PORT}:${PORT}"
        depends_on:
            - db
        volumes:
            - ./:/app
        restart: always
        command: npm run web
    db:
        image: postgres:12.5
        env_file: .env
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"